module.exports = {
    images: {
        domains: [
            "i.imgur.com",
            "images.unsplash.com",
            "freepik.com",
            "img.freepik.com",
            "images.pexels.com",
            "static.tildacdn.com",
            "frankfurt.apollo.olxcdn.com",
            "cdn.pixabay.com",
            "panorama-restoran.kz",
            "tennis-astana.kz",
            "paydacard.kz",
            "moto.tours",
            "nekuhnya.ru",
            "avkusa.ru",
            "photos-mt.kcdn.kz",
            "videoagent.ru",
            "tz-spb-video.ru",
            "topzvuk.com",
            "lh3.googleusercontent.com",
            "f11-studio.com",
            "mobile.photoprocenter.ru",
            "m-holl.ru",
            "photoleviosa.com",
            "i.siteapi.org",
            "bash.today",
            "images.satu.kz",
            "flaggr.ru",
            "skadi.kz",
            "uaprokat.in.ua",
            "k2tour.ru",
            "larenda.kz",
            "content1.rozetka.com.ua",
            "dol-sport.ru",
            "pesh-lesh.com",
            "xfreedom.ru",
            "naprokat24.ru",
            "unitsolutions.ru",
            "radiosfera.net",
            "4club.com.ua",
            "photos-mt.kcdn.kz",
            "cdn0.youla.io",
            "kz.all.biz",
            "ru.thai-moto.com",
            "lease-je-scooter.nl",
            "tradeinn.com",
            "cdn.shopify.com",
        ],
    },
    env: {
        API_HOST: process.env.API_HOST,
        API_BACK: process.env.API_BACK,
    },
};
